name: Build
on:
   push:
     branches: [ 'main' ]
     paths-ignore: [ 'docs/**' ]

permissions: write-all

env:
  VERSION: 0.0.1

jobs:
  geoblockingMiddleware:
    name: GeoblockingMiddleware
    runs-on: macos-12
    env:
      SLN_FILE: GeoblockingMiddleware.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build ${SLN_FILE} -p:Version=${VERSION}-nightly-${GITHUB_RUN_ID} --no-restore --configuration Release
    - name: Test
      run: dotnet test ${SLN_FILE} -p:Version=${VERSION}-nightly-${GITHUB_RUN_ID} --no-build --configuration Release
